import GlassCard from '../components/GlassCard';
import { Sparkles, ArrowRight, Zap, CheckCircle2 } from 'lucide-react';

const Recommendation = () => {
  const recommendations = [
    {
      title: 'Initiate VIP Plan Upsell for Enterprise Cohort',
      impact: 'High (+ $45k ARR)',
      confidence: '96% Confidence',
      description: '245 accounts have reached 90% resource utilization limit. Automated outreach recommended.',
      category: 'Upsell'
    },
    {
      title: 'Trigger Retention Sequence for Inactive Accounts',
      impact: 'Medium (Save $18k ARR)',
      confidence: '89% Confidence',
      description: '112 users have not logged in for 14+ days. Send personalized AI re-engagement playbook.',
      category: 'Churn Prevention'
    },
    {
      title: 'Promote New API Analytics Feature',
      impact: 'High (+ Engagement)',
      confidence: '92% Confidence',
      description: 'Developers in Startup Segment show high API activity. Display feature highlight banner in-app.',
      category: 'Feature Adoption'
    }
  ];

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-2xl font-bold text-white flex items-center gap-2">
          <Sparkles className="h-6 w-6 text-cyan-400" /> Prescriptive AI Recommendations
        </h1>
        <p className="text-sm text-slate-400">Real-time recommended actions generated by deep-learning models.</p>
      </div>

      <div className="space-y-4">
        {recommendations.map((item, idx) => (
          <GlassCard key={idx} className="border-l-4 border-l-cyan-500">
            <div className="flex flex-col md:flex-row justify-between md:items-center gap-4">
              <div className="space-y-1">
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-cyan-500/20 text-cyan-400 uppercase">{item.category}</span>
                  <span className="text-xs font-semibold text-emerald-400">{item.impact}</span>
                  <span className="text-xs text-slate-500">• {item.confidence}</span>
                </div>
                <h3 className="text-base font-semibold text-white">{item.title}</h3>
                <p className="text-xs text-slate-400">{item.description}</p>
              </div>

              <button className="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 px-4 py-2.5 text-xs font-semibold text-white shadow-lg shadow-cyan-500/20 hover:opacity-90 whitespace-nowrap">
                Execute Action <ArrowRight className="h-3.5 w-3.5" />
              </button>
            </div>
          </GlassCard>
        ))}
      </div>
    </div>
  );
};

export default Recommendation;