import {
  ResponsiveContainer,
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
} from "recharts";

import { TrendingUp } from "lucide-react";

const RevenueChart = ({ data = [] }) => {
  return (
    <div
      className="
space-y-6
"
    >
      {/* TOP SUMMARY */}

      <div
        className="
flex
items-center
justify-between
"
      >
        <div>
          <p
            className="
text-sm
text-gray-500
"
          >
            Total Revenue
          </p>

          <h2
            className="
mt-2
text-3xl
font-semibold
text-white
"
          >
            $2.4M
          </h2>
        </div>

        <div
          className="
flex
items-center
gap-2
rounded-full
border
border-white/10
bg-white/5
px-4
py-2
text-sm
text-gray-300
"
        >
          <TrendingUp size={16} />
          +12.5%
        </div>
      </div>

      {/* CHART */}

      <div
        className="
h-[300px]
w-full
rounded-2xl
border
border-white/10
bg-black/20
p-4
"
      >
        <ResponsiveContainer width="100%" height="100%">
          <AreaChart
            data={data}
            margin={{
              top: 20,

              right: 10,

              left: -20,

              bottom: 0,
            }}
          >
            <defs>
              <linearGradient id="revenueGradient" x1="0" y1="0" x2="0" y2="1">
                <stop offset="0%" stopColor="#ffffff" stopOpacity={0.2} />

                <stop offset="100%" stopColor="#ffffff" stopOpacity={0} />
              </linearGradient>
            </defs>

            <CartesianGrid
              stroke="rgba(255,255,255,0.06)"
              strokeDasharray="3 3"
            />

            <XAxis
              dataKey="month"
              stroke="#666"
              tickLine={false}
              axisLine={false}
            />

            <YAxis stroke="#666" tickLine={false} axisLine={false} />

            <Tooltip
              contentStyle={{
                background: "#0B0B0B",

                border: "1px solid rgba(255,255,255,0.12)",

                borderRadius: "18px",

                padding: "12px",

                color: "#fff",
              }}
            />

            <Area
              type="monotone"
              dataKey="revenue"
              stroke="#ffffff"
              strokeWidth={2.5}
              fill="url(#revenueGradient)"
              dot={{
                r: 4,

                fill: "#ffffff",

                stroke: "#050505",

                strokeWidth: 2,
              }}
            />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      <p
        className="
text-xs
text-gray-500
"
      >
        Revenue forecast generated by AI prediction models
      </p>
    </div>
  );
};

export default RevenueChart;
